### ISSUE TITLE
add docker options

### ISSUE THREAD

**Issue by ctaggart** [matthieudelaro/nut#11]
Is there a way to pass in `--security-opt seccomp=unconfined` or other docker options? In order for delve to work, I need to do something like:
```
docker run --rm -it --security-opt seccomp=unconfined ctaggart/golang-vscode:0.0.2 su - vscode
```
https://github.com/derekparker/delve/issues/515#issuecomment-214958141

**Comment by matthieudelaro** [comment]
Not yet. Nut doesn't rely on docker CLI, but only on Docker API. As a result, each parameter has to be added as follow: 
- it should be added to project_v5.go to be parsed from nut.yml
- core.go should pass the parameter of the project to docker API
- project_base.go should implement stub values for the new parameter
