### ISSUE TITLE
ERRO[0000] Error while starting container, and attaching to it: API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}

### ISSUE THREAD

**Issue by mattscilipoti** [matthieudelaro/nut#17]
`ERRO[0000] Error while starting container, and attaching to it: API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}`

To reproduce: 
- clone this repo
- `$ cd nut`
- `$ nut test`
- or `$ nut build-osx`

ENV:
- nut version 0.1.3 dev (via npm)
- Docker version 1.12.0-rc2, build 906eacd, experimental (Docker for OSX, https://docs.docker.com/engine/installation/mac/)
- osx 10.11.5

**Comment by mattscilipoti** [comment]
Found this: https://docs.docker.com/engine/deprecated/#hostconfig-at-api-container-start

**Comment by mattscilipoti** [comment]
Looks like we need to move the HostConfig from Start to Create.

**Comment by mattscilipoti** [comment]
Looks like go-dockerclient has been updated: https://github.com/fsouza/go-dockerclient/issues/537

**Comment by matthieudelaro** [comment]
Thanks for reporting the issue and for investigating a solution. It was indeed this problem.

**Comment by mattscilipoti** [comment]
Thanks for fixing it!  Sorry I wasn't much help with the coding.  Your fix is similar to what I was trying, I just didn't know how to update the dependency that needed the change.  The update that adds a dependency manifest, with a version for each dependency, looks like a move in the right direction (I'm still learning about the Go environment).  From reviewing this commit, it looks like it was an impetus to add some more error handling.  That's usually a good thing.

Thanks for all your efforts with nut.  I believe this is a "good thing".
