### ISSUE TITLE
Error: segmentation fault when trying to run nut on macOS Mojave (10.14.6)

### ISSUE THREAD

**Issue by davidgarsan** [matthieudelaro/nut#35]
Anytime I try to launch on OSX from terminal I got this `segmentation fault  ./nut run` error.

**Comment by matthieudelaro** [comment]
Hello @davidgarsan ,

Thanks for reaching out to warn about this issue.
Have you ever had this issue before? Which version of nut are you running?

I'd like to reproduce your issue to help you. But I never encountered such an issue, even thou I'm using nut on my Mac, which is running OSX 10.14.5. Have you ever experienced the issue with this version on OSX?

Would you mind sharing you nut file? And any file related to it?

Thanks by advance

**Comment by davidgarsan** [comment]
Hi @matthieudelaro,  
Thanks for answering
My OSX version is 10.14.6, and is the first time I use this tool.
My first attempt was to use the [npm](https://github.com/RnbWd/nut-bin) solution which lead me to the commented error.
Instead of NPM, I tried to build Nut from source code and is apparently working.

**Comment by matthieudelaro** [comment]
Ok, nice to hear you found a solution to your problem.
